### ISSUE TITLE
ES Module error: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by puchm** [wclr/ts-node-dev#265]
## Issue description
I am looking at porting some projects to ESM and I don't know what I am doing wrong. This is the full error:
```
(node:10732) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\Moritz\Documents\Programming\esmtest\main.ts:1
import cryptoRandomString from 'crypto-random-string';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:355:18)
    at wrapSafe (node:internal/modules/cjs/loader:1039:15)
    at Module._compile (node:internal/modules/cjs/loader:1073:27)
    at Module._compile (C:\Users\Moritz\Documents\Programming\esmtest\node_modules\source-map-support\source-map-support.js:547:25)
    at Module.m._compile (C:\Users\Moritz\AppData\Local\Temp\ts-node-dev-hook-06833675296542485.js:69:33)
    at Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at require.extensions.<computed> (C:\Users\Moritz\AppData\Local\Temp\ts-node-dev-hook-06833675296542485.js:71:20)
    at Object.nodeDevHook [as .ts] (C:\Users\Moritz\Documents\Programming\esmtest\node_modules\ts-node-dev\lib\hook.js:63:13)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
[ERROR] 20:21:04 SyntaxError: Cannot use import statement outside a module
```
## Context

*OS version (is it docker or host?), ts-node-dev version* Windows 10 Home

*Did you try to run with [ts-node](https://github.com/TypeStrong/ts-node)*?
Yes, this is what I tried:
` npx ts-node main.ts` returned:
```
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for C:\Users\Moritz\Documents\Programming\esmtest\main.ts
    at new NodeError (node:internal/errors:363:5)
    at Loader.defaultGetFormat [as _getFormat] (node:internal/modules/esm/get_format:71:15)
    at Loader.getFormat (node:internal/modules/esm/loader:105:42)
    at Loader.getModuleJob (node:internal/modules/esm/loader:243:31)
    at Loader.import (node:internal/modules/esm/loader:177:17)
    at Object.loadESM (node:internal/process/esm_loader:68:5)
```

However `node --loader ts-node/esm main.ts` worked.

*Did you try to run with `--files` option enabled?*
Yes, no changes

*Did you try to run with `--debug` option enabled?*
Yes, nothing special

*Do you have a repro example (git repo) with simple steps to reproduce your problem?*
Yes, here: https://github.com/puchm/ts-node-dev-esm-test

Just run `npm start`

**Comment by CikiMomogi** [comment]
I got the same error. In my case, changing the option in  `tsconfig.json` 

from:
`{
  "compilerOptions": {
    "module": "es2020"
  }
}`
to:
`{
  "compilerOptions": {
    "module": "commonjs"
  }
}`
fixed the issue.

As mentioned on https://github.com/TypeStrong/ts-node/issues/922#issuecomment-765008102
> So all in all this can be summarized as: Using TypeScript, node.js and the TypeScript compiler option "module": "esnext" together is next to impossible. So if you're building code that should be ran with node.js, in 2020, you should still choose "module": "commonjs".

**Comment by Cretezy** [comment]
This is a major blocking issue for us, and we're considering switching away from ts-node-dev (which worked perfectly in the past) as many dependencies are switching to ESM.

We are using:

In `package.json`: `"type": "module"`

In `tsconfig.json`: `"module": "ES2020"`

And we are getting: `SyntaxError: Cannot use import statement outside a module`

**Comment by wesgladwell** [comment]
Same issue here. This needs to be updated.

**Comment by ivawzh** [comment]
Same issue

**Comment by HerilS** [comment]
Any update to this. The issue is still persistent in the package.

**Comment by jianhao** [comment]
I also encounter this problem, so when will ESM be supported?

**Comment by johanolandero** [comment]
A workaround is to override compiler options for ts-node and keep TS compiling to module type of choice

Can be done within `tsconfig.json`
```js
// tsconfig.json

{
  "compilerOptions": {
    "module": "es2020",
    // ... rest of config
  },
  "ts-node": {
    "compilerOptions": {
      "module": "commonjs"
    }
  }
}
```
---
ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 4.4.2)

**Comment by lukeberry99** [comment]
I still get issues when using ESM only modules with the above config from @johanolandero. Is there any progress on `ts-node-dev` supporting ES2020 and `type: module` yet? Or is there a suggested project to migrate to?

**Comment by SrBrahma** [comment]
ESM is being a nightmare for me. The solution of @johanolandero doesn't work if you are using `import [...] .js` to suit ESM in the project as some libs require it.

**Comment by trickstival** [comment]
I have the same problem when trying to run mocha tests with ts-node

**Comment by damianobarbati** [comment]
Did anybody find a solution to this mess?

**Comment by spiffytech** [comment]
If your compile time is quick you can instruct nodemon to restart your app using the ts-node ESM loader:

```bash
nodemon --exec 'node --loader ts-node/esm' src/index.ts
```

Otherwise, you can use `tsc --watch` and have something watch the compiled output. My preferred way to do this is to combine [`npm-run-all`](https://www.npmjs.com/package/npm-run-all) with [`watchexec`](https://github.com/watchexec/watchexec) (you can do this with nodemon, you'll just have to do a full build before you start nodemon)

```json
"scripts": {
    "server:build:dev": "tsc -w",
    "server:watch": "watchexec --postpone --restart --debounce 250 --no-vcs-ignore --filter 'dist/**/*' 'node dist/index.js'",
    "server:serve": "npm-run-all --parallel server:build:dev server:watch",
}
```

**Comment by tsourtzis** [comment]
> A workaround is to override compiler options for ts-node and keep TS compiling to module type of choice
> 
> Can be done within `tsconfig.json`
> 
> ```js
> // tsconfig.json
> 
> {
>   "compilerOptions": {
>     "module": "es2020",
>     // ... rest of config
>   },
>   "ts-node": {
>     "compilerOptions": {
>       "module": "commonjs"
>     }
>   }
> }
> ```
> 
> ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 4.4.2)

This doesn't help since that's for ts-node options not for ts-node-dev, the issue still persists even today for me, can't get top-level to work properly sadly, waiting for an update that will allow us the save behaviour in tsconfig.json as ts-node provides already.

**Comment by angelhdzmultimedia** [comment]
> > A workaround is to override compiler options for ts-node and keep TS compiling to module type of choice
> > Can be done within `tsconfig.json`
> > ```js
> > // tsconfig.json
> > 
> > {
> >   "compilerOptions": {
> >     "module": "es2020",
> >     // ... rest of config
> >   },
> >   "ts-node": {
> >     "compilerOptions": {
> >       "module": "commonjs"
> >     }
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 4.4.2)
> 
> This doesn't help since that's for ts-node options not for ts-node-dev, the issue still persists even today for me, can't get top-level to work properly sadly (works perfectly with ts-node, the fact is that ts-node-dev doesn't do that), waiting for an update that will allow us the save behaviour in tsconfig.json as ts-node provides already.
> 
> Will probably try to figure this out more or simply change to something like nodemon that's already mentioned.

I managed to get everything working with Nodemon + Babel + Babel TypeScript plugins/presets. And I think the solution also involves ts-node, can't remember now.

Yeah confirmed it, it uses ts-node: `nodemon -I --exec node --experimental-specifier-resolution=node  --loader ts-node/esm ./src/main.ts`.

I hope this gets solved soon as I want to keep using ts-node-dev but I need ESM and top level await and all the good stuff from EcmaScript Next.

### Update
I've been lately using the following approach which is fast and smooth:
`nodemon --exec node --loader ts-node/esm src/main.ts`.

**Comment by pravesa** [comment]
### Solution

To use the `native ESM support of the node` within our typescript project and to transpile with `ts-node`,  we have to reconfigure the `package.json` and `tsconfig.json` accordingly.

In `package.json`,

```diff
{
-  "type": "commonjs"
+  "type": "module"
}
```

In `tsconfig.json`,

```diff
{
  "compilerOptions": {
-    "module": "CommonJS"
+    "module": "ESNext" // or ES2015, ES2020
  },
  "ts-node": {
+    "esm": true
  }
}
```

`Note:`
- without `"type": "module"` in package.json, we get `SyntaxError: Cannot use import statement outside a module` error
- without `"esm": true` in tsconfig.json but package.json reconfigured, we get `TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts"` error

**Comment by carlocorradini** [comment]
@pravesa Unfortunately throws an error: `ERR_UNSUPPORTED_DIR_IMPORT` 😥

**Comment by pravesa** [comment]
@carlocorradini  This error might be caused while resolving your imported module path. So, could you provide your exact error stack

**Comment by angelhdzmultimedia** [comment]
> ### Solution
> To use the `native ESM support of the node` within our typescript project and to transpile with `ts-node`, we have to reconfigure the `package.json` and `tsconfig.json` accordingly.
> 
> In `package.json`,
> 
> ```diff
> {
> -  "type": "commonjs"
> +  "type": "module"
> }
> ```
> 
> In `tsconfig.json`,
> 
> ```diff
> {
>   "compilerOptions": {
> -    "module": "CommonJS"
> +    "module": "ESNext" // or ES2015, ES2020
>   },
>   "ts-node": {
> +    "esm": true
>   }
> }
> ```
> 
> `Note:`
> 
> * without `"type": "module"` in package.json, we get `SyntaxError: Cannot use import statement outside a module` error
> * without `"esm": true` in tsconfig.json but package.json reconfigured, we get `TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts"` error

### Sadly this doesn't work for me.

I have everything configured correctly, type module in package.json, target and module to ESNext in tsconfig, moduleResolution to node, esModuleInterop true, allowSyntheticImports true, and `"ts-node": { esm: true }`

Then in my scripts:
"dev": "ts-node-dev --respawn src/main.ts"

And I get the error that I posted many times in this repository:

`Must use import to load ES Module.`

With nodemon and ts-node I got it working this way:
`nodemon --exec node --loader ts-node/esm src/main.ts`

No issues so far.

**Comment by carlocorradini** [comment]
Same error as @angelhdzmultimedia
@pravesa I obtain `ERR_UNSUPPORTED_DIR_IMPORT` error when simply running `ts-node ...`.
Supporting `top-level-await` could be super cool and very (very) useful.

**Comment by angelhdzmultimedia** [comment]
> nodemon --exec node --loader ts-node/esm src/main.ts

Install `nodemon `and `ts-node` while the ts-node-dev team solves this issue. You'll enjoy top level await and other goodies.

Then in your script:

`"dev": "nodemon --exec node --loader ts-node/esm src/main.ts"`

![image](https://user-images.githubusercontent.com/10191085/195943548-f0d314c9-106f-46ff-95c3-d5a7749d656e.png)

**Comment by pravesa** [comment]
> Same error as @angelhdzmultimedia @pravesa I obtain `ERR_UNSUPPORTED_DIR_IMPORT` error when simply running `ts-node ...`. Supporting `top-level-await` could be super cool and very (very) useful.

@carlocorradini  I hope that the error message you get in your terminal is like this,
`CustomError: ERR_UNSUPPORTED_DIR_IMPORT <file_path_in_your_project_that_is_imported> <file_that_has_import_statement>`

So, to resolve this I need your exact error stack

**Comment by carlocorradini** [comment]
@pravesa Running with `ts-node-dev` I obtain the same error as @angelhdzmultimedia
Running with "pure" `ts-node` I obtain the following error:

![immagine_2022-10-15_113235325](https://user-images.githubusercontent.com/21266147/195979463-d52246c2-c8ac-44ae-bafe-c6f92bf68084.png)

PS: the project is available [here](https://github.com/carlocorradini/reCluster/tree/main/server)

**Comment by pravesa** [comment]
> @pravesa Running with `ts-node-dev` I obtain the same error as @angelhdzmultimedia Running with "pure" `ts-node` I obtain the following error:
> 
> ![immagine_2022-10-15_113235325](https://user-images.githubusercontent.com/21266147/195979463-d52246c2-c8ac-44ae-bafe-c6f92bf68084.png)
> 
> PS: the project is available [here](https://github.com/carlocorradini/reCluster/tree/main/server)

@carlocorradini  `nodejs` resolves module path in `ESM type` with some additional rules.  So, refactor `imports` and `exports` in  typescript project as follows to solve your issue,

### example directory
```
my-app
├── package.json
│ 
└── src
    ├── logger
    │   ├── logger.ts
    │   └──  index.ts
    ├── somefile.ts
    └── main.ts
```
#### NOTE --> `import` and `export` statements should have `full path` and `.js` extensions for files,

### example.
```js
// exporting a file inside `/logger/index.ts`
export somefeature from 'logger.js';

 // importing (from) file
import 'somefile.js'; 
import somefeature from 'logger.js';

// importing a subdirectory (full path should be specified)
import { loggerfeature } from './logger/index.js';
```

If the file doesn't have `.js` extension in export or import statement you will get `ERR_MODULE_NOT_FOUND` error, while for subdirectory import without full path (incl. `index.js`) you will get `ERR_UNSUPPORTED_DIR_IMPORT` error.

Hope, this will resolves your problem.

**Comment by warcayac** [comment]
> > nodemon --exec node --loader ts-node/esm src/main.ts
> 
> Install `nodemon `and `ts-node` while the ts-node-dev team solves this issue. You'll enjoy top level await and other goodies.
> 
> Then in your script:
> 
> `"dev": "nodemon --exec node --loader ts-node/esm src/main.ts"`
> 
> ![image](https://user-images.githubusercontent.com/10191085/195943548-f0d314c9-106f-46ff-95c3-d5a7749d656e.png)

Hi @angelhdzmultimedia, I like your theme, is it applied to IDE only or desktop in general? what theme are you using (for VSCode and OS)? is it on a Linux distro?

**Comment by angelhdzmultimedia** [comment]
> > > nodemon --exec node --loader ts-node/esm src/main.ts
> > 
> > 
> > Install `nodemon `and `ts-node` while the ts-node-dev team solves this issue. You'll enjoy top level await and other goodies.
> > Then in your script:
> > `"dev": "nodemon --exec node --loader ts-node/esm src/main.ts"`
> > ![image](https://user-images.githubusercontent.com/10191085/195943548-f0d314c9-106f-46ff-95c3-d5a7749d656e.png)
> 
> Hi @angelhdzmultimedia, I like your theme, is it applied to IDE only or desktop in general? what theme are you using (for VSCode and OS)? is it on a Linux distro?

One Dark Theme and the GlassIt extension to make the window transparent.

**Comment by hyoretsu** [comment]
Same `Must use import to load ES Module.` error, please fix.
